services:
  web:
    build: .
    command: fastapi dev llmchat/main.py 
      --host 0.0.0.0 
      --port 8000 
      --reload
    volumes:
      - .:/llmchat
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A llmchat.main.celery_app worker --loglevel=info
    volumes:
      - .:/llmchat
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:7