services:
  web:
    build: .
    command: uvicorn aichatui/main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./data:/aichatui/data
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A aichatui.main.celery_app worker --loglevel=info
    volumes:
      - .:/aichatui
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:7
    